version: '3.9'

services:
  app:
    build: .
    container_name: php_app
    volumes:
      - ./index.php:/var/www/html/index.php
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: find_sport
      MYSQL_USER: find_sport_user
      MYSQL_PASSWORD: find_sport_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
